main: net.nifheim.yitan.itemlorestats.Main
name: LoncoLoreItems
version: ${project.version}
author: YitanTribal, Beelzebu
description: The RPG Core of Nifheim Minecraft
softdepend: [ActionBarAPI, WorldGuard, Vault, Citizens, ArmorWeight, MVdWPlaceholderAPI]
commands:
  ils:
    description: The core ILS command.
permissions:
  ils.admin: 
    description: Player/group is granted admin privilege.
    default: op
  ils.repair:
    description: Allows players to use the /ils repair command.
    default: op
  ils.commandlist:
    description: Allows players to use the /ils command to view the available ils commands.
    default: op