main: net.nifheim.yitan.itemlorestats.Main
name: LoncoLoreItems
version: ${project.version}
author: YitanTribal, Beelzebu
description: The RPG Core of Nifheim Minecraft
softdepend: [WorldGuard, Vault, Citizens, MythicMobs]
commands:
  ils:
    description: The core ILS command.
  test:
    description: Command for tests
  character:
    description: Characters base command
permissions:
  ils.admin: 
    description: Player/group is granted admin privilege.
    default: op
  ils.repair:
    description: Allows players to use the /ils repair command.
    default: op
  ils.commandlist:
    description: Allows players to use the /ils command to view the available ils commands.
    default: op
    
 # Honor:
     # Calc = while diff < 5 = 5×((2^diff)×0,5)
     # 5 lvls = -5 hp
     # 